   eureka:
      instance:
              hostname: localhost
      client:
            registerWithEureka: true
            fetchRegistry: true
            preferIpAddress: true
            serviceURL:
                      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant_db
    username: root
    password: tiger
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
