server:
   port: 8761    
eureka:
      instance:
              hostname: localhost
      client:
            registerWithEureka: true
            fetchRegistry: true
            preferIpAddress: true
            serviceURL:
                      defaultZone: http://localhost:8761/eureka
