server:
   port: 8761    
eureka:
      instance:
              hostname: localhost
      client:
            registerWithEureka: false
            fetchRegistry: false
            preferIpAddress: true
            serviceURL:
                      defaultZone: http://localhost:8761/eureka
