   eureka:
      instance:
              hostname: localhost
      client:
            registerWithEureka: true
            fetchRegistry: true
            preferIpAddress: true
            serviceURL:
                      defaultZone: http://localhost:8761/eureka
                     
                     
datasource: 
  url: jdbc:mysql://localhost:3306/restaurant_db
  username: root
  password: tiger
 jpa:
  hibernate.ddl-auto: update
  generate-ddl: true
  show-sql: true
